name: google_maps_utils
description: 
  Initial version comes with the 3 main Classes. SphericalUtils, MathUtils and PolyUtils, calculating bounds, distances headings and many more.

homepage: https://github.com/KohlsAdrian/google_maps_utils/
version: 1.4.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'